### PR TITLE
DSE 5.1.37 Release

### PR DESCRIPTION
**Pull request by szymon-miezal**
----
## Release Notes Automation
If you name your pull-request as "Product x.y.z Release ...", after merging the
PR, a GitHub Action will automatically create a product version tag "product-x.y.z".

Supported product names are:
 * DSE
 * OpsCenter
 * Studio
 * Luna Streaming

Version supports 3 sets or 4 sets of digits.

### CODE REVIEW

**Comment by szymon-miezal** [comment]
I have found that https://github.com/datastax/release-notes/pull/97/files#diff-c4f90fa02c12ae5093175389478ce3b775086ca26bc1d97c356142315a9649e7 contains a lot of `UNKNOWN` licenses, we will have to improve the release notes generator or fill them by hand.

**Comment by tiagomlalves** [comment]
@szymon-miezal Didn't `release-notes-generator` issued warnings for all the missing cases? Did you use `DSP-23034-snyk-support` branch?

**Comment by szymon-miezal** [comment]
@tiagomlalves I did use `DSP-23034-snyk-support` as the master still uses fossa. I have got some warnings but I haven't checked if all the `UNKNOWN` licenses were reported.

**Comment by tiagomlalves** [comment]
@szymon-miezal we should fix issues such that all warnings are removed - did you look into the `README.md` for instructions? Let me know if I can help.

**Pull request merged**
